export const FETCH_RATES_REQUEST = `FETCH_RATES_REQUEST`
export const FETCH_RATES_SUCCESS = `FETCH_RATES_SUCCESS`
export const FETCH_RATES_FAILURE = `FETCH_RATES_FAILURE`
export const SET_FROM_CURRENCY_INDEX = `SET_FROM_CURRENCY_INDEX`
export const SET_TO_CURRENCY_INDEX = `SET_TO_CURRENCY_INDEX`
export const SET_AMOUNT_TO_CONVERT = `SET_AMOUNT_TO_CONVERT`
